version: "3"
services:
    frontend:
        build:
            context: ./frontend
        expose:
            - 5000
        networks:
            - proxy
            - internal  # Solo accesible para micros
        restart: always


    micro-1:
        build:
            context: ./backend/micro-1
        expose:
            - 3001
        networks:
            - internal  # Solo accesible para frontend
        restart: always


    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - "./nginx/certs:/etc/nginx/ssl:ro"
          - "./nginx/conf.d:/etc/nginx/conf.d:ro"
        depends_on:
            - frontend
        networks:
          - proxy
        restart: always

networks:
  proxy:
    driver: bridge
  internal:
    internal: true  #Red interna, inaccesible desde fuera